### ISSUE TITLE
request : RISCV64 support

### ISSUE THREAD

**Issue by wprayudo** [hermit-os/kernel#100]
any planning for supporting RISCV64 arch ? RISCV64 multicore and manycore may become potential for multi-kernel feature

**Comment by stlankes** [comment]
I am playing around with RISCV64. But due to lack of time this will hardly be feasible.

**Comment by jounathaen** [comment]
I see a possible thesis topic here :grin:

**Comment by garrettgu10** [comment]
@stlankes we're a group of UT Austin students working on a project for a Virtualization class, and we're interested in picking this issue up. 🙂

**Comment by stlankes** [comment]
This will be great. But I am not able to help you. I can explain the structure of RustyHermit, but I am not huge expert in RISCV64. @jounathaen has more experiences. But I don't know if he has time.

**Comment by garrettgu10** [comment]
I think we're good on the RISC-V, we will definitely take you up on the structure. Is Slack the best way to reach you? 😊

**Comment by stlankes** [comment]
Yes, I like slack ;-)

**Comment by wprayudo** [comment]
rayon example from libhermit itself already show that risc-v is a cool combinations, along with multicores and manycore architecture :)
