### ISSUE TITLE
TryFromIntError: virtqueue BufferElem capacity overflows u16

### ISSUE THREAD

**Issue by m-mueller678** [hermit-os/kernel#1514]
My workload hits a TryFromIntError in `hermit::drivers::virtio::virtqueue::BufferElem::capacity`. I am not sure why this function assumes the capacity would fit in an u16?

**Comment by mkroening** [comment]
Thanks for opening the issue! I have opened https://github.com/hermit-os/kernel/pull/1515. I'll do some more digging on the history, but I think, we can just change it. `u32` should be correct.
