### ISSUE TITLE
Unsound network driver interface

### ISSUE THREAD

**Issue by mkroening** [hermit-os/kernel#355]
`receive_rx_buffer` returns a static reference, which both implementations just make up. https://github.com/hermitcore/libhermit-rs/blob/7432581905476ee4496409fb2f076055b289ad5e/src/drivers/net/mod.rs#L35-L36

`get_tx_buffer` returns "ownership" with no clear description of what this means. The `usize` represents the buffer in some driver-specific way. There should be an abstraction for those tokens to shift the transmutes to where they are necessary and can be reasoned about. https://github.com/hermitcore/libhermit-rs/blob/7432581905476ee4496409fb2f076055b289ad5e/src/drivers/net/mod.rs#L25-L28

**Comment by stlankes** [comment]
@mkroening We are able to close this issue. I revised the driver for the new IP stack.

**Comment by cagatay-y** [comment]
I am not sure but I think we can close this issue. The interface that was mentioned in the issue description was revised and the virtio driver no longer makes use of unsafe pointer handling.
