### ISSUE TITLE
Replace self-baked Pinned with std::pin

### ISSUE THREAD

**Issue by mkroening** [hermit-os/kernel#668]
https://github.com/hermitcore/libhermit-rs/blob/8802a3fc0a55c12d668618f4cd641421fa9d4228/src/drivers/virtio/virtqueue/mod.rs#L2374-L2389

[std::pin](https://doc.rust-lang.org/stable/std/pin/index.html)

**Comment by joannejchen** [comment]
Hi @mkroening! @scotran and I are part of a Virtualization course at UT Austin, and as part of a project we have to contribute to open source repositories. Can we take up this issue?

**Comment by mkroening** [comment]
Sure, have a go at it! :)

**Comment by mkroening** [comment]
Done in https://github.com/hermit-os/kernel/pull/983.
