### ISSUE TITLE
Replace `AsSliceU8` trait with `zerocopy::AsBytes`

### ISSUE THREAD

**Issue by mkroening** [hermit-os/kernel#692]
Padding is uninitialized: [Glossary - Unsafe Code Guidelines Reference](https://rust-lang.github.io/unsafe-code-guidelines/glossary.html#padding)

We do not check for padding, neither is `AsSliceU8` unsafe.
[`zerocopy::AsBytes`](https://docs.rs/zerocopy/latest/zerocopy/trait.AsBytes.html) performs these checks.

**Comment by joannejchen** [comment]
Hi @mkroening! @scotran and I are part of a Virtualization course at UT Austin, and as part of a project we have to contribute to open source repositories. Can we take up this issue?

**Comment by mkroening** [comment]
Sure, do you want to do all three issues?

PS: To assign @scotran, he has to be a participant of this issue. Just write anything, then I can add him as well.

**Comment by joannejchen** [comment]
Hi @mkroening! I was able to switch the VirtioNetHdr from implementing AsSliceU8 to deriving AsBytes, but I ran into an issue when trying to change from AsSliceU8 to AsBytes for the Cmd and Rsp structs (https://github.com/hermitcore/libhermit-rs/blob/master/src/fs/fuse.rs#L293): #[derive(AsBytes)] is not supported on types with type parameters. Digging around, there seems to be a workaround (https://github.com/google/zerocopy/issues/10), but this would require using repr(transparent), which then cannot be used alongside repr(C) or repr(packed), which would strip padding and possibly cause alignment issue.

I just wanted to touch base first as to whether this would be the desired approach, and if so, I can continue looking into how to derive AsBytes for structs with type parameters.

**Comment by mkroening** [comment]
Just as an aside, there is a proposal for `DynSized`, with a very similar purpose to our `AsSliceU8`: https://github.com/rust-lang/rfcs/pull/3536

**Comment by cagatay-y** [comment]
`AsSliceU8` was removed with #1316. I think we can close this issue.

**Comment by mkroening** [comment]
Superseded by https://github.com/hermit-os/kernel/pull/1316
