### ISSUE TITLE
virtio-net-pci does not detect connection closed by other side

### ISSUE THREAD

**Issue by egrimley-arm** [hermit-os/kernel#880]
Test program `Cargo.toml`:
```
[package]
name = "testtcp"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(target_os = "hermit")'.dependencies.hermit]
version = "0.6.0"
```

Test program `src/main.rs`:
```
#[cfg(target_os = "hermit")]
use hermit as _;

use std::io::Read;
use std::net::TcpListener;

fn main() {
    let listener = TcpListener::bind("127.0.0.1:8080").unwrap();
    let (mut socket, _) = listener.accept().unwrap();
    let mut buf = [0u8; 1000];
    loop {
        println!("about to read");
        match socket.read(&mut buf) {
            Err(e) => {
                println!("read err {e:?}");
                break;
            }
            Ok(n) => {
                println!("read {n}");
                if n == 0 {
                    break;
                }
            }
        }
    }
}
```

Build and run without Hermit:
```
cargo run
```

Test from another terminal (exit socat and close connection with C-c/C-d):
```
$ socat - TCP:localhost:8080
a
bb
$
```

Output:

```
about to read
read 2
about to read
read 3
about to read
read 0
$
```

Build and run with Hermit:
```
cd rusty-loader
cargo xtask build --target x86_64 --release
cd ../testtcp
cargo build --target x86_64-unknown-hermit --release \
  -Z build-std=std,core,alloc,panic_abort \
  -Z build-std-features=compiler-builtins-mem

qemu-system-x86_64 \
    -cpu qemu64,apic,fsgsbase,fxsr,rdrand,rdtscp,xsave,xsaveopt \
    -smp 1 -m 512M \
    -device isa-debug-exit,iobase=0xf4,iosize=0x04 \
    -display none -serial stdio \
    -kernel ../rusty-loader/target/x86_64/release/hermit-loader \
    -initrd target/x86_64-unknown-hermit/release/testtcp \
    -netdev user,id=u1,hostfwd=tcp::8080-:8080 \
    -device virtio-net-pci,netdev=u1,disable-legacy=on
```

Same test. Output:
```
about to read
read 2
about to read
read 3
about to read
```
(und es bleibt hängen!)

I am supposing that this is a problem in Rusty Hermit rather than in QEMU or the system I am testing this on. Any evidence for or against that supposition would be helpful.

**Comment by egrimley-arm** [comment]
For what it's worth, I printed the value of `recv_data` at https://github.com/hermit-os/kernel/blob/0aedc555e72cdd3f18c96ae6a22aaa9e4f770447/src/drivers/net/virtio_net.rs#L579 and saw an IP/TCP packet in which the FIN bit was set: `[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 82, 84, 0, 18, 52, 86, 82, 85, 10, 0, 2, 2, 8, 0, 69, 0, 0, 40, 0, 5, 0, 0, 64, 6, 98, 187, 10, 0, 2, 2, 10, 0, 2, 15, 146, 94, 31, 144, 0, 45, 230, 2, 190, 197, 47, 155, 80, 17, 255, 255, 17, 68, 0, 0]]`

The IP header starts at `69`, the TCP header at `146`, the destination port is `31, 144`, and the first `17` is the flags: ACK and FIN. Decoded by referring to 
https://en.wikipedia.org/wiki/Internet_Protocol_version_4#Header and https://en.wikipedia.org/wiki/Transmission_Control_Protocol#TCP_segment_structure!

**Comment by stlankes** [comment]
Yes, I have the same behavior on my system. I take look in the kernel to solve this issue.

**Comment by stlankes** [comment]
On my system, #881 solve this issue. Maybe the error message can be improved.But this require a modification in Rust's `std`.

**Comment by stlankes** [comment]
Can I add your example in as example in the repository `hermit-os/hermit-rs`?

**Comment by egrimley-arm** [comment]
> On my system, PR #881 solves this issue.

It works for me, too. Thanks!
