### ISSUE TITLE
`sys_sendto` and `sys_recvfrom` are missing

### ISSUE THREAD

**Issue by dpogorzelski** [hermit-os/kernel#967]
When building against hermit 0.7 i'm running into the following linker issues:
rust-lld: error: undefined symbol: sys_sendto
rust-lld: error: undefined symbol: sys_recvfrom

Based on my understanding the default feature set should supply network capabilities via tcp and udp features.
Any ideas as to why I'm still running into the issue?
Should dependencies supplying networking features be calling `use hermit as _;` or it's enough for my crate to do so?
Thanks ! :)

**Comment by mkroening** [comment]
I pinged @stlankes about this again, yesterday. He'll look into this. :)

**Comment by stlankes** [comment]
Yes, I will do it soon!

**Comment by stlankes** [comment]
@mkroening @dpogorzelski If you like, you can test PR #1007
